version: "3.7"
services:
  rstudio:
    image: dplyr-v1-excercises:latest
    build:
      context: docker
    ports:
      - "8787:8787"
    environment:
      - PASSWORD=password
      - DISABLE_AUTH=true
    volumes:
      - .:/home/rstudio/dplyr-v1-excercises
